import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FormWrapper from './components/formWrapper'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className='w-full bg-gray-800 h-auto min-h-screen'>
        <nav className='h-20 bg-black bg-opacity-40 flex justify-center items-center shadow-xl'>
          <h2 className='text-lg text-white   text-center'>What ever you want as header or navbar goes here</h2>
        </nav>

        <div className='w-full h-auto min-h-[calc(100vh-5rem)]  '>
          <FormWrapper/>
        </div>
     </main>
    </>
  )
}
